spring.datasource.url=jdbc:mysql://localhost:3306/negotium_card
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=change-this-secret-key-change-this-secret-key-123456
app.jwt.access-token-expiration=3600000
app.jwt.refresh-token-expiration=1209600000
app.upload.dir=uploads
